# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.0.0-dev
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-09-20T17:40:19Z"
  name: schmnginx
spec:
  containers:
  - image: docker.io/nginx:latest
    name: mynginx
    ports:
    - containerPort: 80
      hostPort: 8080
  - image: docker.io/nginx:latest
    name: auth
    ports:
    - containerPort: 80
      hostPort: 8081
  - image: docker.io/nginx:latest
    name: worst
    ports:
    - containerPort: 80
      hostPort: 8082